snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: redis://172.18.0.1:6379
    doctrine:
        metadata_cache:
            client: default
            entity_manager: default
        result_cache:
            client: default
            entity_manager: default
        query_cache:
            client: default
            entity_manager: default
        second_level_cache:
            client: default
            entity_manager: default