swiftmailer:
    transport: '%env(MAILER_TRANSPORT)%'
    username: '%env(MAILER_USERNAME)%'
    password: '%env(MAILER_PASSWORD)%'
    host: '%env(MAILER_SERVER)%'
    port: '%env(MAILER_PORT)%'
    encryption: '%env(MAILER_ENCRYPTION)%'
    spool:
        type: 'memory'
    logging:              '%kernel.debug%'