# Select image from https://hub.docker.com/_/php/
image: php:7.2

# Select what we should cache
cache:
  paths:
  - vendor/

before_script:
# Install git, the php image doesn't have installed
- apt-get update -yqq
- apt-get install git -yqq

# Install mysql driver
- docker-php-ext-install pgsql

# Install composer
- curl -sS https://getcomposer.org/installer | php

# Install all project dependencies
- php composer.phar install

services:
- pgsql

variables:
  # Configure mysql service (https://hub.docker.com/_/mysql/)
   POSTGRES_USER: 'test'
   POSTGRES_PASSWORD: 'test'

# We test PHP5.6 (the default) with MySQL
test:pgsql:
  script:
  - vendor/bin/phpunit --configuration phpunit_pgsql.xml --coverage-text

# We test PHP7 with MySQL, but we allow it to fail
test:php7:pgsql:
  image: php:7
  script:
  - vendor/bin/phpunit --configuration phpunit_pgsql.xml --coverage-text
  allow_failure: true
