job: 
  tags: 
    - docker
standard: 
  before_script: 
    - "apt-get update && apt-get install -y unzip git"
    - "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\""
    - "php composer-setup.php"
    - "php -r \"unlink('composer-setup.php');\""
    - "php composer.phar install -n --optimize-autoloader --apcu-autoloader"
    - "php composer.phar dump-autoload --optimize --apcu"
  image: "php:7.2-fpm"
  script: 
    - "php composer.phar install --prefer-dist"
    - "php composer.phar require \"squizlabs/php_codesniffer=*\""
    - "vendor/bin/phpcs --standard=PSR1,PSR2 --ignore=src/Domain/Migrations/*,src/DataFixtures/* src/"
  stage: test
test: 
  before_script: 
    - "php -vv"
    - "php -r \"copy('https://getcomposer.org/installer', 'composer-setup.php');\""
    - "php composer-setup.php"
    - "php -r \"unlink('composer-setup.php');\""
    - "php composer.phar install -n --optimize-autoloader --apcu-autoloader"
    - "php composer.phar dump-autoload --optimize --apcu"
    - "apk add --no-cache zlib-dev"
    - "docker-php-ext-configure zlib --with-dir/usr/local/zlib \\ && docker-php-ext-install zip"
    - "docker-php-ext-install zip"
  image: "php:fpm-alpine"
  script: 
    - "php bin/phpunit --coverage-text -v"
    - "vendor/bin/behat -v"
  stage: test