language: php
php:
    - '7.2'
before_script:
    - composer install --no-scripts -n
    - cp .env.dist .env
script:
    - php bin/console d:d:c --env=test
    - php bin/console d:s:c --env=test
    - php bin/console d:f:l -n --env=test
    - php bin/phpunit -v --exclude-group Blackfire
notifications:
email: false