version: 2
jobs:
    phpunit:
        docker:
            - image: circleci/php:7.2.3-apache-node-browsers
        machine:
          php:
            version: 7.2.3
        steps:
            - checkout
            - run: echo 'Hello World'
            - run: sudo apt install -y libsqlite3-dev zlib1g-dev
            - run: sudo docker-php-ext-install zip
            - run: sudo composer self-update
            - restore_cache:
                keys:
                    - composer-v1-{{ checksum "composer.json" }}
                    - composer-v1-
            - run: composer install -n --optimize-autoloader --classmap-authoritative
            - run: composer dump-autoload --optimize --classmap-authoritative
            - save_cache:
                key: composer-v1-{{ checksum "composer.json" }}
                paths:
                    - vendor  
            - run: ./bin/phpunit -v --exclude-group Blackfire

workflows:
    version: 2
    unit_test:
        jobs:
          - phpunit