App\Domain\DTO\MovieDTO:
  properties:
    embed:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['Movie']
    legend:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['Movie']