App\Domain\DTO\RegisterUserDTO:
  constraints:
    - App\Validators\UniqueUserDTO:
       groups: ['RegisterUser']
  properties:
    name:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    username:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    lastname:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    mail:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    password:
    - Regex:
        pattern: '/(?=.*[0-9])(?=.*[a-z].+[a-zA-Z])(?=.*[A-Z])(?=.*[!@#%$&])[\S]{8,}/'
        match: true
        message: "Votre mot de passe doit contenir une lettre majuscule, une lettre minuscule, un caractère spéciale '!@#%$&*', et un chiffre, 8 caractères minimum"
        groups: ['RegisterUser']