App\Domain\DTO\RegisterUserDTO:
  properties:
    name:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    username:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    lastname:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    mail:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']
    password:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['RegisterUser']