App\Domain\Models\Tricks:
    properties:
      name:
        - NotBlank: ~
        - Length:
            min: 3
            groups: ['AddTrick']
      description:
        - NotBlank: ~
        - Length:
            min: 3
            groups: ['AddTrick']