App\Domain\DTO\UpdateTrickDTO:
  properties:
    name:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['UpdateTrick']
    description:
    - NotBlank: ~
    - Length:
        min: 3
        groups: ['UpdateTrick']