App\Domain\DTO\ValidateForgotPasswordDTO:
  properties:
    password:
      - Regex:
          pattern: '/(?=.*[0-9])(?=.*[a-z].+[a-zA-Z])(?=.*[A-Z])(?=.*[!@#%$&])[\S]{8,}/'
          match: true
          message: "Votre mot de passe doit contenir une lettre majuscule, une lettre minuscule, un caractère spéciale '!@#%$&*', et un chiffre, 8 caractères minimum"
          groups: ['ValidateForgotPassword']